[package]
name = "rust-web-api-ddd"
version = "0.1.0"
edition = "2024"



[dependencies]
# Web 框架
axum = "0.8.6"
tower = "0.5.2"
tower-http = { version = "0.6.6", features = ["cors", "trace", "compression-br", "compression-gzip"] }

# 异步运行时
tokio = { version = "1.48.0", features = ["full"] }
async-trait = "0.1.89"

# 数据库
sqlx = { version = "0.8.6", features = ["mysql", "runtime-tokio-rustls", "chrono"] }
diesel = { version = "2.3.2", features = ["mysql", "r2d2", "chrono"] }

# Redis
redis = { version = "1.0.0-rc.3", features = ["tokio-comp", "connection-manager"] }

# 序列化
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

# 配置管理
config = "0.15.18"
dotenvy = "0.15.7"

# 错误处理
anyhow = "1.0.100"
thiserror = "2.0.17"

# 验证
validator = { version = "0.20.0", features = ["derive"] }

# 安全
jsonwebtoken = { version = "10.1.0", features = ["aws_lc_rs"] }
argon2 = { version = "0.5.3", features = ["std"] }
# 日期时间
chrono = { version = "0.4.42", features = ["serde"] }


# 日志
tracing = "0.1"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
# --- 日志输出 ---
log = "0.4.28"
env_logger = "0.11.8"


# 工具
futures = "0.3"
hyper = "1.7.0"

#solana
solana-sdk = "3.0.0"
solana-client ="3.0.8"
spl-token = "8.0.0"
borsh = "0.10.4"
pumpfun = "4.6.0"
# 可选依赖：代币元数据解析（需要时保留）
spl-token-metadata = "0.0.1"



[dev-dependencies]
# 测试依赖 "0.12.8"