[database]
host = "localhost"
port = 3306
username = "root"
password = ""
database_name = "rust_test001"
max_connections = 20

[server]
host = "0.0.0.0"
port = 3000

[app]
jwt_secret = ""
hash_salt = ""

[logging]
level = "info"